### ISSUE TITLE
Space validation

### ISSUE THREAD

**Issue by Ewan-James-Donovan** [redsquirrelstudio/vue-password-checker#1]
Perhaps provide validation for spaces. For example, and invalid state and message that says "Passwords cannot contain spaces."
This may already be a feature, as I've not given this a thorough read, but if it's not, it needs to be. Good stuff, mate.

**Comment by Ewan-James-Donovan** [comment]
See PR

**Comment by redsquirrelstudio** [comment]
Thank you for the fixes, these have been merged and published to npm under 1.1.0
